apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: FEATURE_NAMESPACE  # Будет заменено в workflow

replicas:
- name: web
  count: 1
- name: celery-worker
  count: 1
- name: celery-beat
  count: 1

patchesStrategicMerge:
  - configmap-patch.yaml

images:
- name: cr.yandex/crpfasovola9dqldhpk4/smartmeeting
  newTag: FEATURE_TAG  # Будет заменено в workflow
