apiVersion: v1
kind: ConfigMap
metadata:
  name: smartmeeting-config
env:
  - name: HOST
    valueFrom:
      secretKeyRef:
        name: secrets-project
        key: HOST
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_CSRF_TRUSTED_ORIGINS: "https://smartmeeting.$(HOST),https://smartmeeting.$(HOST)"
  DJANGO_CSRF_COOKIE_SECURE: "True"
  DJANGO_SESSION_COOKIE_SECURE: "True"
  DJANGO_SECURE_SSL_REDIRECT: "True"
  DJANGO_SECURE_HSTS_SECONDS: "31536000"
