apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: smartmeeting-prod

secretGenerator:
- name: secrets-project
  envs:
  - .env.secret
  type: Opaque
  options:
    disableNameSuffixHash: true

patchesStrategicMerge:
  - patches/deployment-web.yaml
  - patches/deployment-worker.yaml
  - patches/service-web.yaml
  - patches/configmap.yaml

images:
- name: cr.yandex/crpfasovola9dqldhpk4/smartmeeting
  newTag: latest
