apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: smartmeeting-prod

secretGenerator:
- name: secrets-project
  envs:
  - .env.secret
  type: Opaque
  options:
    disableNameSuffixHash: true

patches:
- target:
    kind: Deployment
    name: web
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: cr.yandex/crpfasovola9dqldhpk4/smartmeeting:latest

- target:
    kind: Deployment
    name: celery-worker
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

- target:
    kind: Service
    name: web
  patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer

images:
- name: cr.yandex/crpfasovola9dqldhpk4/smartmeeting
  newTag: latest
