apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: smartmeeting-staging

replicas:
- name: web
  count: 2
- name: celery-worker
  count: 1
- name: celery-beat
  count: 1

patchesStrategicMerge:
  - configmap-patch.yaml
  - ingress-patch.yaml

images:
- name: cr.yandex/crpfasovola9dqldhpk4/smartmeeting
  newTag: staging-latest
