apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: smartmeeting-staging

# Патчи для изменения конфигурации
patchesStrategicMerge:
  - patches/deployment-web.yaml
  - patches/deployment-worker.yaml
  - patches/configmap.yaml

# Замена образов
images:
- name: cr.yandex/crpfasovola9dqldhpk4/smartmeeting
  newTag: staging-latest
